[package]
name = "threefish_cli"
version = "0.2.0"
edition = "2021"

[dependencies]
rpassword = "5"
rand = "0.8"
rand_core = "0.6"
argon2 = "0.4"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
zeroize = "1.5"    # <-- add this

